name: Build Members Page

on:
  push:
    branches:
      - main
    paths:
      - 'mitglieder/**'
      - 'scripts/build-members-page.py'
      - '.github/workflows/build-members-page.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      
      - name: Build members page
        env:
          MEMBERS_PASSWORD: ${{ secrets.MEMBERS_PASSWORD }}
        run: |
          echo "🔐 Baue Mitgliederseite..."
          python3 scripts/build-members-page.py
      
      - name: Copy data file
        run: |
          cp mitglieder/mitglieder_data.json mitglieder_data.json
          echo "✅ Datendatei kopiert"
      
      - name: Verify build
        run: |
          echo "🔍 Verifiziere Build..."
          
          if grep -q "MEMBERS_PASSWORD_PLACEHOLDER" mitglieder.html; then
            echo "❌ FEHLER: Platzhalter nicht ersetzt!"
            exit 1
          fi
          
          if [ ! -s mitglieder.html ]; then
            echo "❌ FEHLER: Datei leer!"
            exit 1
          fi
          
          echo "✅ Verifikation erfolgreich"
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [[ -n $(git status --porcelain mitglieder.html mitglieder_data.json) ]]; then
            git add mitglieder.html mitglieder_data.json
            git commit -m "🤖 Auto-build: Mitgliederseite aktualisiert"
            git push
            echo "✅ Änderungen gepusht"
          else
            echo "ℹ️ Keine Änderungen"
          fi
